# Need to download Gemma 4 Template

model: 'cyankiwi/gemma-4-31B-it-AWQ-4bit'
served-model-name:
  - 'stratus.coder'
tensor-parallel-size: 2
gpu-memory-utilization: 0.90
max-model-len: 131072
enable-prefix-caching: True
enable-auto-tool-choice: True
tool-call-parser: 'gemma4'
reasoning-parser: 'gemma4'
async-scheduling: True
max_num_batched_tokens: 4096
chat-template: '/root/tool_chat_template_gemma4.jinja'
