model: 'deepseek-ai/DeepSeek-V4-Flash-DSpark'
served-model-name:
  - 'stratus.thinking'
tensor-parallel-size: 2
gpu-memory-utilization: 0.96
max-model-len: 262144
enable-expert-parallel: True
trust-remote-code: True
moe-backend: 'flashinfer_b12x'
kv-cache-dtype: 'fp8'
#chat-template-kwargs: { "enable_thinking": true, "reasoning_effort": "max" }
speculative-config: { "method": "dspark","num_speculative_tokens": 7,"draft_sample_method": "greedy" }
tokenizer-mode: 'deepseek_v4'
tool-call-parser: 'deepseek_v4'
enable-auto-tool-choice: True
reasoning-parser: 'deepseek_v4'