# Blackwell High VRAM

model: 'unsloth/Qwen3.6-27B-NVFP4'
served-model-name:
  - 'stratus.thinking'
async-scheduling: True
data-parallel-size: 2
enable-auto-tool-choice: True
enable-chunked-prefill: True
gpu-memory-utilization: 0.9
kv-cache-dtype: 'fp8'
load-format: 'fastsafetensors'
max-model-len: 262144
max-num-batched-tokens: 8192
max-num-seqs: 8
override-generation-config: { "temperature": 0.55 }
reasoning-parser: 'qwen3'
speculative-config: { "method": "mtp", "num_speculative_tokens": 3 }
tool-call-parser: 'qwen3_xml'
