model: 'cyankiwi/Qwen3.6-35B-A3B-AWQ-4bit'
served-model-name:
  - 'stratus.turbo'
default-chat-template-kwargs: {"enable_thinking": false}
enable-expert-parallel: True
enable-auto-tool-choice: True
gpu-memory-utilization: 0.85
kv-cache-dtype: 'fp8'
max-model-len: 65536
max-num-batched-tokens: 4096
override-generation-config: {"temperature": 0.7, "top_p": 1.0, "top_k": 40, "presence_penalty": 2.0}
reasoning-parser: 'qwen3'
speculative-config: { "method": "mtp", "num_speculative_tokens": 2 }
tensor-parallel-size: 2
tool-call-parser: 'qwen3_xml'
