# Need to download Gemma 4 Template
# https://github.com/vllm-project/vllm/blob/e203006a8b05b6380f7deb261c28f384711674c1/examples/tool_chat_template_gemma4.jinja

model: 'cyankiwi/gemma-4-31B-it-AWQ-4bit'
served-model-name:
  - 'stratus.gemma'
tensor-parallel-size: 2
gpu-memory-utilization: 0.90
max-model-len: 262144
enable-prefix-caching: True
enable-auto-tool-choice: True
tool-call-parser: 'gemma4'
reasoning-parser: 'gemma4'
async-scheduling: True
dtype: 'half'
max_num_batched_tokens: 4096
chat-template: '/root/tool_chat_template_gemma4.jinja'
