# This Requires 2 x NVIDIA RTX 6000 Pro Blackwell

model: 'nvidia/MiniMax-M2.7-NVFP4'
served-model-name:
  - 'stratus.thinking'
tensor-parallel-size: 2
gpu-memory-utilization: 0.95
max-model-len: 262144
enable-expert-parallel: True
enable-auto-tool-choice: True
tool-call-parser: 'minimax_m2'
reasoning-parser: 'minimax_m2'
