# Blackwell High Performance
model: 'cyankiwi/Qwen3.6-27B-AWQ-INT4'
served-model-name:
  - 'stratus.coder'
data-parallel-size: 2
gpu-memory-utilization: 0.93
max-model-len: 262144
enable-prefix-caching: True
enable-auto-tool-choice: True
tool-call-parser: 'qwen3_coder'
reasoning-parser: 'qwen3'
dtype: 'half'
override-generation-config: {"temperature": 0.6}