model: cyankiwi/Qwen3.6-35B-A3B-AWQ-4bit
served-model-name:
  - 'stratus.turbo'
tensor-parallel-size: 2
gpu-memory-utilization: 0.90
max-model-len: 131072
enable-expert-parallel: True
enable-auto-tool-choice: True
enable-prefix-caching: True
tool-call-parser: 'qwen3_coder'
reasoning-parser: 'qwen3'
kv-cache-dtype: 'fp8'
max-num-batched-tokens: 4096
default-chat-template-kwargs: '{"enable_thinking": false}'
override-generation-config: '{"temperature": 0.7, "top_p": 1.0, "top_k": 40, "presence_penalty": 2.0}'