# Blackwell High VRAM
model: 'Qwen/Qwen3.6-27B-FP8'
served-model-name:
  - 'stratus.coder'
data-parallel-size: 2
gpu-memory-utilization: 0.95
max-model-len: 262144
enable-auto-tool-choice: True
tool-call-parser: 'qwen3_coder'
reasoning-parser: 'qwen3'
kv-cache-dtype: 'fp8'
override-generation-config: {"temperature": 0.6}